### ISSUE TITLE
Errors when upload video + text prompt. Also errors before can give me a 2nd reply.

### ISSUE THREAD

**Issue by bladedsupernova** [NExT-GPT/NExT-GPT#1]

**Comment by bladedsupernova** [comment]
What happened is I asked it for a video of a text prompt, adn then when ask it for another such video tot ry agian ir erros every time.

Also, when ask it "Make me an audio track to give to this video:" for the video I then upload with that text inptu together, even on the first blank go it errors, with nothing even written yet on the page.

But inputting just "hello", works, even now.

**Comment by scofield7419** [comment]
Hi, first thank you for trying out the demo.

For your feedback: 
Yes it sometimes produces undesired output, e.g., return errors or decline to produce multimodal content. We may largely attribute this issue to the instability of the current initial version of NExT-GPT, limited by the quantity of fine-tuning data and the quality of the base models. This is especially the case when the input prompt entails much implicit intention. Mostly, I will change the input prompts, to make them more precise, and then things get much better. 

In our following version, the model will be optimized, and the generated content will be better.
Thanks!
