### ISSUE TITLE
Why train each modal separately?

### ISSUE THREAD

**Issue by linyifan123456** [NExT-GPT/NExT-GPT#10]
Thank you for the release of the code! According to README: "--mm_root_path .../.../x, x varies from [images, audios, videos]", it seems that, for three stages, data from different modals is trained separately. Is it reasonable?

**Comment by scofield7419** [comment]
Hi @linyifan123456, very sensitive question, good one. We in this version simply train the system under each modality separately. We just followed the existing training code logic, and did it separately as it works not bad.
But we are aware of the possible negative impact of catastrophic forgetting this brought. We believe training with mixed modal data could be much better as can be expected.  (We haven't yet implemented the mixing batches of different modalities. Welcome to contribute via pull requests.)
