### ISSUE TITLE
NEW CODE BROKEN

### ISSUE THREAD

**Issue by anonymous-atom** [NExT-GPT/NExT-GPT#102]
@ChocoWu We have been testing and using old legacy code from NExT-GPT,  but yesterday I tried the latest code and thought to use it, but the predict.py seems to be unusable and very confusing.

The https://github.com/NExT-GPT/NExT-GPT/blob/main/nextgpt/model/builder.py#L26C5-L26C26 (load_pretrained_model()) function is where all the issue is.

How can we use the latest code for inference using vicuna weights and the next-gpt weights from huggingface.

Any help is highly appreciated.

**Comment by ChocoWu** [comment]
@anonymous-atom. The weights currently on Huggingface are for the older codebase. The new checkpoint will be uploaded soon with the updated version—stay tuned!

**Comment by anonymous-atom** [comment]
Thanks for that! Also can you let me know the corresponsing code for your prompt_wrap() function which was in your old repo ?

**Comment by anonymous-atom** [comment]
Yeah

**Comment by anonymous-atom** [comment]
@ChocoWu 
Getting below error whenever I am trying to train the encoder side, the issues seems to occur while passing the input to imagebind, even though the shape shape of input to be passed to imagebind seems to be correct,


  File "/NExT-GPT/train.py", line 569, in <module>
    train()
  File "/NExT-GPT/train.py", line 536, in train
    trainer.train()
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/transformers/trainer.py", line 2268, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/transformers/trainer.py", line 3307, in training_step
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/transformers/trainer.py", line 3338, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1899, in forward
    loss = self.module(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpt/model/language_model/nextgpt_llama.py", line 210, in forward
    outputs = self._get_output(
              ^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpt/model/language_model/nextgpt_llama.py", line 158, in _get_output
    ) = self.prepare_inputs_labels_for_multimodal(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpt/model/nextgpt_arch.py", line 418, in prepare_inputs_labels_for_multimodal
    video_features = self.encode_videos(concat_videos)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpt/model/nextgpt_arch.py", line 376, in encode_videos
    video_features = self.get_model().get_multimodal_tower()(videos, modality='video')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpt/model/multimodal_encoder/imagebind_encoder.py", line 79, in forward
    embeddings = self.multimodal_tower(_inputs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpt/model/multimodal_encoder/ImageBind/models/imagebind_model.py", line 475, in forward
    modality_value = self.modality_heads[modality_key](
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/NExT-GPT/nextgpts/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3855x1279 and 1280x1024)

**Comment by anonymous-atom** [comment]
I also tried with the latest commit, but still getting this error

**Comment by koookieee** [comment]
@ChocoWu  Yeah, I am also getting the same error while training the encoder

**Comment by ChocoWu** [comment]
@anonymous-atom @koookieee I just correct the error, please try again.

**Comment by anonymous-atom** [comment]
Sure, thanks for that, checking it out

**Comment by anonymous-atom** [comment]
Still doesn't seems to work

**Comment by ChocoWu** [comment]
It's working fine on my end. What does the error log say on your side?

**Comment by anonymous-atom** [comment]
Yup Thanks! it's working now

**Comment by koookieee** [comment]
@ChocoWu  Thank you so much, it works for me too now!

**Comment by Kiri0824** [comment]
> @anonymous-atom. The weights currently on Huggingface are for the older codebase. The new checkpoint will be uploaded soon with the updated version—stay tuned!

Is there a plan for when the new checkpoint will be released?

**Comment by 1903812532** [comment]
@ChocoWu 运行 PyTorch 训练脚本 train.py 时遇到了一个断言错误（AssertionError）。错误发生在 common/utils.py 文件的 l2_loss 函数中，具体是因为两个张量 u 和 v 的形状不匹配。 AssertionError: (torch.Size([1, 77, 768]), torch.Size([1, 77, 1024]))

**Comment by Kiri0824** [comment]
> @ChocoWu 运行 PyTorch 训练脚本 train.py 时遇到了一个断言错误（AssertionError）。错误发生在 common/utils.py 文件的 l2_loss 函数中，具体是因为两个张量 u 和 v 的形状不匹配。 AssertionError: (torch.Size([1, 77, 768]), torch.Size([1, 77, 1024]))

你能成功运行demo_app.py吗,输入的音频或图像信息可以正常分析吗

**Comment by 1903812532** [comment]
> > 运行 PyTorch 训练脚本 train.py 时遇到了一个断言错误（AssertionError）。错误发生在 common/utils.py 文件的 l2_loss 函数中，具体是因为两个张量 u 和 v 的形状不匹配。AssertionError： （火炬.大小（[1， 77， 768]），火把。大小 （[1， 77， 1024]））
> 
> 你能成功运行demo_app.py吗，输入的音频或图像信息可以正常分析吗
我之前成功运行过demo_app.py,但是它连基本的文字问答都很困难，其他模态不能分析

**Comment by 1903812532** [comment]
> > > 运行 PyTorch 训练脚本 train.py 时遇到了一个断言错误（AssertionError）。错误发生在 common/utils.py 文件的 l2_loss 函数中，具体是因为两个张量 u 和 v 的形状不匹配。AssertionError： （火炬.大小（[1， 77， 768]），火把。大小 （[1， 77， 1024]））
> > 
> > 
> > 你能成功运行demo_app.py吗，输入的音频或图像信息可以正常分析吗 我之前成功运行过demo_app.py，但是它连基本的文字问答都很困难，其他模态不能分析

于是我开始训练，利用60个数据，但是我在训练第二阶段遇到了困难

**Comment by Kiri0824** [comment]
> > > > 运行 PyTorch 训练脚本 train.py 时遇到了一个断言错误（AssertionError）。错误发生在 common/utils.py 文件的 l2_loss 函数中，具体是因为两个张量 u 和 v 的形状不匹配。AssertionError： （火炬.大小（[1， 77， 768]），火把。大小 （[1， 77， 1024]））
> > > 
> > > 
> > > 你能成功运行demo_app.py吗，输入的音频或图像信息可以正常分析吗 我之前成功运行过demo_app.py，但是它连基本的文字问答都很困难，其他模态不能分析
> 
> 于是我开始训练，利用60个数据，但是我在训练第二阶段遇到了困难

我明白了,我也是,但我看到这个模型和pandagpt在推理的时候框架非常像,pandagpt是没什么问题的,可以支持多模态,我就以为是不是我哪里参数设置错了,我看到好多人也有类似问题,作者说后面会放出13B的模型,不知道在新框架下13B模型效果会不会好一些.我都是基于2023年的commit,也就是现在仓库中NExT-GPT-Lagacy做的

**Comment by Kiri0824** [comment]
> > > 运行 PyTorch 训练脚本 train.py 时遇到了一个断言错误（AssertionError）。错误发生在 common/utils.py 文件的 l2_loss 函数中，具体是因为两个张量 u 和 v 的形状不匹配。AssertionError： （火炬.大小（[1， 77， 768]），火把。大小 （[1， 77， 1024]））
> > 
> > 
> > 你能成功运行demo_app.py吗，输入的音频或图像信息可以正常分析吗
> > 我之前成功运行过demo_app.py,但是它连基本的文字问答都很困难，其他模态不能分析

你说的文字问答很困难指的是输出的内容不是正常语言还是答非所问呢,我的看起来文字或许是正常的,我测试加入音频或图像模态不能分析

**Comment by koookieee** [comment]
Hi @ChocoWu , i wanted to confirm one thing regarding the dataset. For the llava dataset, do we just need the llava-instruct150k with coco images or the pretrained llava dataset too since there's a  function preprocess_llava_pretrain?
Thanks!

**Comment by anonymous-atom** [comment]
Hi @ChocoWu , when the data for MoSIT will be released ?

**Comment by ChocoWu** [comment]
> Hi @ChocoWu , when the data for MoSIT will be released ? Also did you train on 2M or 10M WebVid samples ?

The MoSIT can be found in [here](https://github.com/NExT-GPT/NExT-GPT/blob/main/data/IT_data/MosIT_data/mosit.json).

Yes, during the encoding-side and decoding-side training,  we use 10M webvid samples.

**Comment by anonymous-atom** [comment]
How about the images/videos/audios for MOSIT ?

**Comment by 1903812532** [comment]
> > 嗨，MoSIT 的数据何时发布？您还使用 2M 或 10M WebVid 样本进行了训练吗？
> 
> MoSIT [可以在这里找到](https://github.com/NExT-GPT/NExT-GPT/blob/main/data/IT_data/MosIT_data/mosit.json)。
> 
> 是的，在编码端和解码端训练期间，我们使用了 10M webvid 样本。

你好，我在新代码训练第三阶段使用mosit_instruction_tuning.json文件时，被提示出现缺少'conversations'，可是我发现mosit_instruction_tuning.json文件里是存在的 ，您能告诉我如何解决它吗
Loading datasets...
{'data_path': './data/IT_data/T-T+X_data/audio_instruction_tuning.json', 'audio_caption_emb_folder': './data/it/embed/', 'video_caption_emb_folder': './data/it/embed/', 'image_caption_emb_folder': './data/it/embed/', 'video_folder': './data/T_X_pair_data/webvid/videos', 'audio_folder': './data/T_X_pair_data/audiocap/audios', 'image_folder': './data/T_X_pair_data/cc3m/images'}
{'data_path': './data/IT_data/T-T+X_data/video_instruction_tuning.json', 'audio_caption_emb_folder': './data/it/embed/', 'video_caption_emb_folder': './data/it/embed/', 'image_caption_emb_folder': './data/it/embed/', 'video_folder': './data/T_X_pair_data/webvid/videos', 'audio_folder': './data/T_X_pair_data/audiocap/audios', 'image_folder': './data/T_X_pair_data/cc3m/images'}
{'data_path': './data/IT_data/T-T+X_data/image_instruction_tuning.json', 'audio_caption_emb_folder': './data/it/embed/', 'video_caption_emb_folder': './data/it/embed/', 'image_caption_emb_folder': './data/it/embed/', 'video_folder': './data/T_X_pair_data/webvid/videos', 'audio_folder': './data/T_X_pair_data/audiocap/audios', 'image_folder': './data/T_X_pair_data/cc3m/images'}
{'data_path': './data/IT_data/T+X-T_data/llava/preprocessed_llava.json', 'image_folder': './data/IT_data/T+X-T_data/llava/images', 'audio_caption_emb_folder': './data/it/embed/', 'video_caption_emb_folder': './data/it/embed/', 'image_caption_emb_folder': './data/it/embed/', 'video_folder': None, 'audio_folder': None}
{'data_path': './data/IT_data/T+X-T_data/alpaca/preprocessed_alpaca.json', 'audio_caption_emb_folder': './data/it/embed/', 'video_caption_emb_folder': './data/it/embed/', 'image_caption_emb_folder': './data/it/embed/', 'video_folder': None, 'audio_folder': None, 'image_folder': './data/llava-150k/images'}
{'data_path': './data/IT_data/T+X-T_data/videochat/videochat.json', 'video_folder': '../data/IT_data/T+X-T_data/videochat/video', 'audio_caption_emb_folder': './data/it/embed/', 'video_caption_emb_folder': './data/it/embed/', 'image_caption_emb_folder': './data/it/embed/', 'image_folder': None, 'audio_folder': None}
{'data_path': './data/IT_data/MosIT_data/mosit_instruction_tuning.json', 'audio_caption_emb_folder': './data/it/embed/', 'video_caption_emb_folder': './data/it/embed/', 'image_caption_emb_folder': './data/it/embed/', 'video_folder': None, 'audio_folder': None, 'image_folder': './data/IT_data/MosIT_data/images'}
cumulative_sizes:  [9599, 19225, 28692, 186404, 238406, 249595, 254299]
<nextgpt.dataset.base_dataset.LazySupervisedDataset object at 0x7f093cc487c0>
<nextgpt.dataset.base_dataset.LazySupervisedDataset object at 0x7f093cc49fc0>
<nextgpt.dataset.base_dataset.LazySupervisedDataset object at 0x7f093cc4a050>
<nextgpt.dataset.base_dataset.LazySupervisedDataset object at 0x7f093cc4a020>
<nextgpt.dataset.base_dataset.LazySupervisedDataset object at 0x7f0914e8faf0>
<nextgpt.dataset.base_dataset.LazySupervisedDataset object at 0x7f0914e8fb20>
Traceback (most recent call last):
  File "/output/NExT-GPT/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "/output/NExT-GPT/train.py", line 534, in train
    trainer.train()
  File "/usr/local/envs/nextgpt/lib/python3.10/site-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
  File "/usr/local/envs/nextgpt/lib/python3.10/site-packages/transformers/trainer.py", line 1961, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/envs/nextgpt/lib/python3.10/site-packages/transformers/trainer.py", line 899, in get_train_dataloader
    dataloader_params["sampler"] = self._get_train_sampler()
  File "/output/NExT-GPT/nextgpt_trainer.py", line 159, in _get_train_sampler
    lengths = self.train_dataset.modality_lengths
  File "/output/NExT-GPT/nextgpt/dataset/concat_dataset.py", line 56, in modality_lengths
    length_list.extend(dataset.modality_lengths)
  File "/output/NExT-GPT/nextgpt/dataset/base_dataset.py", line 130, in modality_lengths
    cur_len = sum(len(conv['value'].split()) for conv in sample['conversations'])
KeyError: 'conversations'
[2024-10-20 09:39:59,627] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 5119

**Comment by ChocoWu** [comment]
It works fine on my side, I have no idea about the issue (⊙o⊙)…

**Comment by anonymous-atom** [comment]
Hi @ChocoWu 
During training of the decoder, either of compute_image_loss, compute_video_loss, compute_audio_loss is None, is this because during training the dataloader passes data of 1 modality through forward pass ? Is this the expected behaviour ?

because the loss fluctuates alot:

=== compute_image_loss : (30.875, 30.875, None) ======
=== compute_video_loss : (None, None, None) ======
===compute_audio_loss : (None, None, None) ======
{'loss': 38.7826, 'grad_norm': 47.2336196899414, 'learning_rate': 6.505283282093679e-06, 'epoch': 0.0}  


=== compute_image_loss : (None, None, None) ======
=== compute_video_loss : (None, None, None) ======
===compute_audio_loss : (2.421875, 2.421875, 0.3259783685207367) ======
{'loss': 6.0065, 'grad_norm': 111.6504898071289, 'learning_rate': 6.1332575503138975e-06, 'epoch': 0.0}
