### ISSUE TITLE
cant install scipy==1.14.2

### ISSUE THREAD

**Issue by jellyfishovo** [NExT-GPT/NExT-GPT#108]
I encountered two issues while preparing the environment. First, in the official command:

# CUDA 12.1
conda install pytorch==2.1.2 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia

What exactly does this mean? Should the environment use CUDA 11.6 or 12.1? The second issue is that when I tried installing the requirements in another environment, I got an error saying that scipy==1.14.2 couldn't be installed. At that time, I was using Python 3.8. What kind of environment do I need to meet the configuration requirements? Please update the specific environment requirements and package dependencies.

**Comment by jellyfishovo** [comment]
OK, I resolved this issue by installing the dependencies of the older version of the code, i.e., NExT-GPT-Lagacy. However, the issue I am currently encountering is as follows: I am unable to load the properly fine-tuned Vicuna weights. Based on the previous version’s code comments, I modified my `--nextgpt_ckpt_path` path. My code structure is as follows: 

├── NExT-GPT-Lagacy
│   ├── README.md
│   ├── ckpt
│   │   ├── __init__.py
│   │   ├── delta_ckpt
│   │   │   └── nextgpt
│   │   │       └── 7b_tiva_v0
│   │   │           ├── README.md
│   │   │           ├── __init__.py
│   │   │           ├── added_tokens.json
│   │   │           ├── config.json
│   │   │           ├── pytorch_model.pt
│   │   │           ├── special_tokens_map.json
│   │   │           ├── tokenizer.model
│   │   │           └── tokenizer_config.json
│   │   └── pretrained_ckpt
│   │       ├── __init__.py
│   │       ├── imagebind_ckpt
│   │       │   ├── __init__.py
│   │       │   └── huge
│   │       │       ├── __init__.py
│   │       │       └── imagebind_huge.pth
│   │       ├── prepare_vicuna.md
│   │       └── vicuna_ckpt
│   │           ├── 7b_v0
│   │           │   ├── config.json
│   │           │   ├── generation_config.json
│   │           │   ├── model-00001-of-00003.safetensors
│   │           │   ├── model-00002-of-00003.safetensors
│   │           │   ├── model-00003-of-00003.safetensors
│   │           │   ├── model.safetensors.index.json
│   │           │   ├── special_tokens_map.json
│   │           │   ├── tokenizer.model
│   │           │   └── tokenizer_config.json
│   │           ├── llama-7b
│   │           │   ├── LICENSE
│   │           │   ├── README.md
│   │           │   ├── config.json
│   │           │   ├── generation_config.json
│   │           │   ├── model-00001-of-00002.safetensors
│   │           │   ├── model-00002-of-00002.safetensors
│   │           │   ├── model.safetensors.index.json
│   │           │   ├── pytorch_model-00001-of-00002.bin
│   │           │   ├── pytorch_model-00002-of-00002.bin
│   │           │   ├── pytorch_model.bin.index.json
│   │           │   ├── special_tokens_map.json
│   │           │   ├── tokenizer.json
│   │           │   ├── tokenizer.model
│   │           │   └── tokenizer_config.json
│   │           ├── vicuna-7b-delta-v0
│   │           │   ├── README.md
│   │           │   ├── config.json
│   │           │   ├── generation_config.json
│   │           │   ├── pytorch_model-00001-of-00002.bin
│   │           │   ├── pytorch_model-00002-of-00002.bin
│   │           │   ├── pytorch_model.bin.index.json
│   │           │   ├── special_tokens_map.json
│   │           │   ├── tokenizer.model
│   │           │   └── tokenizer_config.json
│   │           └── vicuna_ckpt
│   │               └── 7b_v0
│   │                   ├── config.json
│   │                   ├── generation_config.json
│   │                   ├── model-00001-of-00003.safetensors
│   │                   ├── model-00002-of-00003.safetensors
│   │                   ├── model-00003-of-00003.safetensors
│   │                   ├── model.safetensors.index.json
│   │                   ├── special_tokens_map.json
│   │                   ├── tokenizer.model
│   │                   └── tokenizer_config.json
│   ├── code
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   │   ├── header.cpython-310.pyc
│   │   │   └── header.cpython-39.pyc
│   │   ├── bot.png
│   │   ├── config
│   │   │   ├── __init__.py
│   │   │   ├── __pycache__
│   │   │   │   └── __init__.cpython-39.pyc
│   │   │   ├── base.yaml
│   │   │   ├── stage_1.yaml
│   │   │   ├── stage_2.yaml
│   │   │   └── stage_3.yaml
│   │   ├── dataset
│   │   │   ├── T+X-T_instruction_dataset.py
│   │   │   ├── T-T+X_instruction_dataset.py
│   │   │   ├── __init__.py
│   │   │   ├── audiocap_dataset.py
│   │   │   ├── base_dataset.py
│   │   │   ├── catalog.py
│   │   │   ├── cc3m_dataset.py
│   │   │   ├── concat_dataset.py
│   │   │   ├── preprocess_dataset.py
│   │   │   ├── samplers.py
│   │   │   ├── utils.py
│   │   │   └── webvid_dataset.py
│   │   ├── demo_app.py
│   │   ├── dsconfig
│   │   │   ├── stage_1.json
│   │   │   ├── stage_2.json
│   │   │   └── stage_3.json
│   │   ├── header.py
│   │   ├── inference.py
│   │   ├── model
│   │   │   ├── ImageBind
│   │   │   │   ├── CODE_OF_CONDUCT.md
│   │   │   │   ├── CONTRIBUTING.md
│   │   │   │   ├── LICENSE
│   │   │   │   ├── README.md
│   │   │   │   ├── __init__.py
│   │   │   │   ├── __pycache__
│   │   │   │   │   ├── __init__.cpython-39.pyc
│   │   │   │   │   └── data.cpython-39.pyc
│   │   │   │   ├── bpe
│   │   │   │   │   └── bpe_simple_vocab_16e6.txt.gz
│   │   │   │   ├── data.py
│   │   │   │   ├── model_card.md
│   │   │   │   ├── models
│   │   │   │   │   ├── __init__.py
│   │   │   │   │   ├── __pycache__
│   │   │   │   │   │   ├── __init__.cpython-39.pyc
│   │   │   │   │   │   ├── helpers.cpython-39.pyc
│   │   │   │   │   │   ├── imagebind_model.cpython-39.pyc
│   │   │   │   │   │   ├── multimodal_preprocessors.cpython-39.pyc
│   │   │   │   │   │   └── transformer.cpython-39.pyc
│   │   │   │   │   ├── helpers.py
│   │   │   │   │   ├── imagebind_model.py
│   │   │   │   │   ├── multimodal_preprocessors.py
│   │   │   │   │   └── transformer.py
│   │   │   │   └── requirements.txt
│   │   │   ├── __init__.py
│   │   │   ├── __pycache__
│   │   │   │   ├── ...
│   │   │   ├── agent.py
│   │   │   ├── anyToImageVideoAudio.py
│   │   │   ├── blip2.py
│   │   │   ├── common
│   │   │   │   ├── __init__.py
│   │   │   │   ├── __pycache__
│   │   │   │   │   ├── __init__.cpython-39.pyc
│   │   │   │   │   └── utils.cpython-39.pyc
│   │   │   │   ├── logger.py
│   │   │   │   └── utils.py
│   │   │   ├── custom_ad.py
│   │   │   ├── custom_sd.py
│   │   │   ├── custom_vd.py
│   │   │   ├── layers.py
│   │   │   ├── modeling_llama.py
│   │   │   └── qformer.py
│   │   ├── nextgpt.png
│   │   ├── process_embeddings.py
│   │   ├── scripts
│   │   │   ├── app.sh
│   │   │   └── train.sh
│   │   ├── train.py
│   │   └── user.png
│   ├── data
│   │   ├── DATA_README.md
│   │   ├── IT_data
│   │   │   ├── MosIT_data
│   │   │   │   ├── __init__.py
│   │   │   │   ├── construction
│   │   │   │   │   ├── chatgpt.py
│   │   │   │   │   ├── demonstrations
│   │   │   │   │   │   ├── T_A.txt
│   │   │   │   │   │   ├── T_A_I.txt
│   │   │   │   │   │   ├── T_A_V.txt
│   │   │   │   │   │   ├── T_I.txt
│   │   │   │   │   │   ├── T_I_V_A.txt
│   │   │   │   │   │   ├── T_V.txt
│   │   │   │   │   │   ├── T_V_I.txt
│   │   │   │   │   │   ├── more_topics.txt
│   │   │   │   │   │   └── topics.txt
│   │   │   │   │   ├── process_data.py
│   │   │   │   │   └── utils.py
│   │   │   │   ├── mosit.json
│   │   │   │   └── mosit_instruction_tuning.json
│   │   │   ├── T+X-T_data
│   │   │   │   ├── __init__.py
│   │   │   │   ├── alpaca
│   │   │   │   │   └── __init__.py
│   │   │   │   ├── llava
│   │   │   │   │   └── prapare.md
│   │   │   │   └── videochat
│   │   │   │       └── __init__.py
│   │   │   └── T-T+X_data
│   │   │       ├── __init__.py
│   │   │       ├── audio_instruction_tuning.json
│   │   │       ├── audio_t2x.json
│   │   │       ├── construction
│   │   │       │   ├── IT-demos.txt
│   │   │       │   ├── chatgpt.py
│   │   │       │   ├── processing_log.py
│   │   │       │   └── utils.py
│   │   │       ├── image_instruction_tuning.json
│   │   │       ├── image_t2x.json
│   │   │       ├── prepare.md
│   │   │       ├── video_instruction_tuning.json
│   │   │       └── video_t2x.json
│   │   ├── T_X_pair_data
│   │   │   ├── audiocap
│   │   │   │   ├── audiocap.json
│   │   │   │   ├── audiocap_comprehension.json
│   │   │   │   ├── audiocap_generation.json
│   │   │   │   ├── audios
│   │   │   │   │   ├── ...
│   │   │   │   └── prepare.md
│   │   │   ├── cc3m
│   │   │   │   ├── cc3m.json
│   │   │   │   ├── cc3m_comprehension.json
│   │   │   │   ├── cc3m_generation.json
│   │   │   │   ├── images
│   │   │   │   │   ├── ...
│   │   │   │   └── prepare.md
│   │   │   └── webvid
│   │   │       ├── config.yaml
│   │   │       ├── download.sh
│   │   │       ├── prepare.md
│   │   │       ├── preprocess.sh
│   │   │       ├── videos
│   │   │       │   ├── ...
│   │   │       ├── webvid.json
│   │   │       ├── webvid_comprehension.json
│   │   │       └── webvid_generation.json
│   │   ├── embed
│   │   │   ├── ...
│   │   └── prepare_data.py
│   ├── demo.py
│   ├── figures
│   │   ├── demo.png
│   │   └── framework.png
│   └── requirements.txt
└── outputtree.txt

I set `--nextgpt_ckpt_path` to `pretrained_ckpt/vicuna_ckpt/vicuna-7b-delta-v0`. However, the program still cannot run properly. After completing the initialization of the tokenizer, the following error message is displayed:

`Traceback (most recent call last):
  File "/root/autodl-tmp/v2/NExT-GPT/NExT-GPT-Lagacy/code/demo_app.py", line 32, in <module>
    delta_ckpt = torch.load(os.path.join(args['nextgpt_ckpt_path'], f'pytorch_model.bin.index.json'), map_location=torch.device('cpu'))
  File "/root/miniconda3/envs/v3/lib/python3.9/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/v3/lib/python3.9/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
`
In my `vicuna_ckpt/llama-7b` folder, there are the original weights of `llama-7b`, downloaded according to the `NExT-Lagacy/README.md` . The `vicuna_ckpt/vicuna-7b-delta-v0` contains the fine-tuned weights, also downloaded according to the  `NExT-Lagacy/README.md`. The `vicuna_ckpt/vicuna_ckpt/7b-v0` contains the merged weights, created following the merging instructions provided in the `NExT-Lagacy/README.md`. Additionally, `vicuna_ckpt/7b_v0` is a copy of `vicuna_ckpt/vicuna_ckpt/7b-v0`, and both contain identical content.

**Comment by Liumucan** [comment]
Hello, could you please run the project now? The current data preparation instructions appear to be problematic. Do you have any suggestions for deploying this project? Thank you.

**Comment by Liumucan** [comment]
Hi, can you run the project now? The current data preparation instructions appear to be problematic. Do you have any suggestions for deploying this project? Thank you.

**Comment by rishieraj** [comment]
I am having the same confusion of CUDA versions. I believe as a result, I am not able to set up the environment for this project.
