### ISSUE TITLE
code structure

### ISSUE THREAD

**Issue by Nischalj10** [NExT-GPT/NExT-GPT#11]
the code structure is very cool and makes it easy to understand the repo. Was wondering how did you generate it? Did you make it manually?

**Comment by scofield7419** [comment]
Hi @Nischalj10, thx for that! 
Did you ever try the [`tree`](https://en.wikipedia.org/wiki/Tree_(command)) command? Try print the directory structure with `tree`.

**Comment by Nischalj10** [comment]
Ohh. I did not. Thanks for that @scofield7419!
