### ISSUE TITLE
Hardware resources and training time

### ISSUE THREAD

**Issue by chiho-5** [NExT-GPT/NExT-GPT#13]
It seems like the total training time and hardware used was not stated in the paper or the webpage. Can you say more about this?.

**Comment by ChocoWu** [comment]
Hi, thx for your attention. As in our practice, the training of NExT-GPT was not all done in one go (involves multiple stages and multiple datasets), it is not simple to conclude how long the training costs. But I can show you some data points.
The training of NExT-GPT was conducted on different hardware, i.e., NVIDIA Tesla V100 (32G), A100 (40G/80G), etc.
On the V100 (32G), FYI:
- For encoding-side alignment, 3x GPUs, batch size 18, takes ≈30 mins on 40k instances of text-X pairs.
- For decoding-side alignment, 3x GPUs, batch size 18, takes ≈3 hours on 180k instances of text-X pairs.
- For instruction tuning, 4x GPUs, batch size 4, takes ≈5 hours on 250k instances.
The instruction tuning, though no need for full-scale param updating, still requires loading all params into memory. So multiple GPUs are still needed. If having A100-80G x8, with a larger batch size, the training will be better and faster.
