### ISSUE TITLE
Suggestion: Expand Model Outreach with hosting Gradio demo on HuggingFace Hub 

### ISSUE THREAD

**Issue by yvrjsharma** [NExT-GPT/NExT-GPT#14]
Hi 🤗 !
Congratulations! Very cool work with Gradio demo linked on the Readme! It would be nice to host the awesome demo on the [Hugging Face Hub](https://huggingface.co/spaces) !

Some of the benefits of sharing your models through the Hub would be:
- A wider reach of your work to the ecosystem
- Seamless integration with popular libraries and frameworks, enhancing usability
- Real-time feedback and collaboration opportunities with a global community of researchers and developers

This is a [step-by-step guide](https://huggingface.co/docs/hub/spaces-sdks-gradio) explaining the process in case you're interested. 😊 This is our docs on [Community GPU Grants](https://huggingface.co/docs/hub/spaces-gpus#community-gpu-grants).

![image](https://github.com/NExT-GPT/NExT-GPT/assets/48665385/caa32ffe-b124-44e6-a20a-5189b1a15d7d)

**Comment by scofield7419** [comment]
Hi @yvrjsharma , thanks for your nice suggestion. We now considering deploying on Space. But will do it later, e.g., when the stable version is confirmed.

**Comment by yvrjsharma** [comment]
Thanks for your reply. I understand. However, I would still encourage you to host on Spaces. You can release an initial demo, iterate (and update versions) on it on Huggingface Hub, collaborate with the community, work on user issues etc. just like you do on Github. 
Linking Spaces docs here for your use- https://huggingface.co/docs/hub/spaces
