### ISSUE TITLE
About audio and video special token

### ISSUE THREAD

**Issue by Dorniwang** [NExT-GPT/NExT-GPT#15]
I found that the special tokens "<Vid>", " </Vid>", "<Aud>", "</Aud>" you added to tokenizer were not used in promot_warp and _prepare_xxx_embed, only "<Img>", "/Img>" used in both video and audio cases. so it seems to be unnecessary to define them ?

**Comment by ChocoWu** [comment]
Hello @Dorniwang , good question. Yes, defining them is not really required. 
For the special tokens, we initially designed three distinct types of tokens to be added to the tokenizer to differentiate the embeddings of the video, image, or audio. But later, in our experiments, we found that using the same special tokens ('<Img></Img>') is just enough, as we use the same multimodal encoder (ImageBind) which aligns the embedding of each modality with the image embeddings.

**Comment by Dorniwang** [comment]
Ok, thanks a lot. 
By the way, i have no idea why the tokens i type in this issue are disappeard : )
