### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by zc-zhao** [NExT-GPT/NExT-GPT#17]
What is the number of GPUs you use during each stage of training?
Could you release the log file during training?

**Comment by ChocoWu** [comment]
Hello, we used different hardware for training the NExT-GPT actually, e.g., NVIDIA Tesla V100 (32G), A100 (40G/80G). FYI, I can show you some data points on the V100 (32G):
- For encoding-side alignment, 3x GPUs, batch size 18, takes ≈30 mins on 40k instances of text-X pairs.
- For decoding-side alignment, 3x GPUs, batch size 18, takes ≈3 hours on 180k instances of text-X pairs.
- For instruction tuning, 4x GPUs, batch size 4, takes ≈5 hours on 250k instances. 

So above is quite a lower-bound of hardware usage, FYI. You can use as many GPUs as you want so long as you have. The training of NExT-GPT, though no need for full-scale param updating, still requires loading all params into memory. So multiple GPUs are still needed. If having A100-80G x8, with larger batch size, the training will be much better and faster.

**Comment by ChocoWu** [comment]
@cydal , thx.

My training order is Stage 1 -> Stage 3 -> Stage 2. 

After adding modality signal tokens, it is necessary to resize the embedding.
https://github.com/NExT-GPT/NExT-GPT/blob/b005e807b4b9086557eca1c386e5b643154b6f7f/code/model/anyToImageVideoAudio.py#L100
After this process, the parameters of `LLM's embedding layer` and the` lm_head` used for next_token prediction become trainable. Thus, the training in Stage 2 will guide the LLM to generate signal tokens.

**Comment by vhzy** [comment]
> lm_head

Hello, I have some questions for you. Do all three stages require LLM's embedding layer and lm_head? Does the paper not introduce the calculation of the parameter quantities here?
