### ISSUE TITLE
7b_tiva_v0

### ISSUE THREAD

**Issue by AItechnology** [NExT-GPT/NExT-GPT#22]
the holiday is coming, can you release 7b_tiva_v0 model today? Thanks

**Comment by ChocoWu** [comment]
Hi, @AItechnology, the NExT-GPT weights are now available in version [7b_tiva_v0](https://huggingface.co/ChocoWu/nextgpt_7b_tiva_v0), feel free to check it out.

**Comment by AItechnology** [comment]
thanks, I will try it soon
