### ISSUE TITLE
Evaluation scripts

### ISSUE THREAD

**Issue by Golovneva** [NExT-GPT/NExT-GPT#23]
Hi! Thank you for releasing code for your model!
Could you please share evaluation scripts as well? Or describe how you ran evals? Thank you!

**Comment by ChocoWu** [comment]
Hello, @Golovneva, thx for your interest. 
Our evaluations entirely refer to the baseline models on different benchmarks correspondingly and separately; you may consult the baseline works for further details if you are eager to the evaluations.
At this point and ahead, we are planning to validate on more tasks and datasets. We think will release all the evaluation approaches in future versions.
