### ISSUE TITLE
Questions for launch demo app.

### ISSUE THREAD

**Issue by molhineko** [NExT-GPT/NExT-GPT#28]
I have one question to launch demo app which is described in [4. Running NExT-GPT System](https://github.com/NExT-GPT/NExT-GPT/tree/fdf1fd8669815bc18c883efda3408098b8df7db3#Run%20NExT-GPT%20System). 
Can I skip [3. Training/Adapting NExt-GPT on Your Own](https://github.com/NExT-GPT/NExT-GPT/tree/fdf1fd8669815bc18c883efda3408098b8df7db3#Training%20on%20Your%20Own) except [3.1. Preparing Pre-trained Checkpoint](https://github.com/NExT-GPT/NExT-GPT/tree/fdf1fd8669815bc18c883efda3408098b8df7db3#31-preparing-pre-trained-checkpoint--back-to-top) for just launching demo app if I use checkpoint which you published in [huggingface](https://huggingface.co/ChocoWu/nextgpt_7b_tiva_v0) ?

**Comment by scofield7419** [comment]
Hi @molhineko , yes you are all good to launch the demo with our checkpoint without training on your side.

**Comment by molhineko** [comment]
Thank you @scofield7419
