### ISSUE TITLE
Package versions have conflicting dependencies

### ISSUE THREAD

**Issue by ouzmno** [NExT-GPT/NExT-GPT#29]
`Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
ERROR: Cannot install PyYAML==6.0 and PyYAML==6.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested PyYAML==6.0
    The user requested PyYAML==6.0.1`

Anyone have any idea which PyYAML version I should loosen to?

**Comment by ChocoWu** [comment]
PyYAML==6.0 is ok.

**Comment by ouzmno** [comment]
> Hi, `PyYAML==6.0` just works fine.

thanks for the reply! 

now, I couldn't find 1.11.2 version scipy even if I search all scipy versions. i was wondering if I could use 1.11.1?
