### ISSUE TITLE
A problem when combineing the weights

### ISSUE THREAD

**Issue by 1920993165** [NExT-GPT/NExT-GPT#31]
(nextgpt) admin1:~/nextgpt/src$ python -m fastchat.model.apply_delta --base llama_hf  --target ./vicuna_ckpt/7b_v0/  --delta vicunaLoading the delta weights from vicuna
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.90s/it]
Loading the base model from llama_hf
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.91s/it]
Applying the delta
Applying delta:   0%|                                                                                                     | 0/291 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/public1/home/stu52275901023/anaconda3/envs/nextgpt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/public1/home/stu52275901023/anaconda3/envs/nextgpt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/public1/home/stu52275901023/anaconda3/envs/nextgpt/lib/python3.8/site-packages/fastchat/model/apply_delta.py", line 165, in <module>
    apply_delta(args.base_model_path, args.target_model_path, args.delta_path)
  File "/public1/home/stu52275901023/anaconda3/envs/nextgpt/lib/python3.8/site-packages/fastchat/model/apply_delta.py", line 140, in apply_delta
    param.data += delta.state_dict()[name]
RuntimeError: The size of tensor a (32000) must match the size of tensor b (32001) at non-singleton dimension 0

**Comment by 1920993165** [comment]
the vicuna's "vocab_size" is 32001?

**Comment by hhllxx1121** [comment]
@1920993165 I had a similar problem,maybe  you can just low your fastchat version with the command ' pip install fschat==0.1.10'

**Comment by 1920993165** [comment]
thx,i guess you are right.
