### ISSUE TITLE
A little question about vicuna weight combine 

### ISSUE THREAD

**Issue by dfgan** [NExT-GPT/NExT-GPT#33]
I followed the instructions  https://github.com/NExT-GPT/NExT-GPT/blob/main/ckpt/pretrained_ckpt/prepare_vicuna.md combine modal, but found that the tensor size is not correct, what should I do here?  “ValueError: Trying to set a tensor of shape torch.Size([32001, 4096]) in "weight" (which has shape torch.Size([32000, 4096])), this look incorrect.”

**Comment by ChocoWu** [comment]
You can find an answer by referring  [here](https://github.com/NExT-GPT/NExT-GPT/issues/31#issuecomment-1751692898).

**Comment by dfgan** [comment]
@ChocoWu  Thanks, your suggestion solved my problem!
