### ISSUE TITLE
train data in stage 3

### ISSUE THREAD

**Issue by zc-zhao** [NExT-GPT/NExT-GPT#36]
I follow [3.2. Preparing Dataset](https://github.com/NExT-GPT/NExT-GPT/tree/main#32-preparing-dataset--back-to-top) to prepare the data. 
  Specifically, for [T2M data](https://github.com/NExT-GPT/NExT-GPT/tree/main#32-preparing-dataset--back-to-top), I use the[ JSON file](https://github.com/NExT-GPT/NExT-GPT/blob/main/data/IT_data/T-T+X_data) you published, but according to [catalog.py](https://github.com/NExT-GPT/NExT-GPT/blob/main/code/dataset/catalog.py), raw multimodal data (such as images) is required to generate embedding, but I am not sure which dataset you are using to generate T2M data. For the images, I thought you were using the CC3M dataset to generate T2M data, but I randomly opened several images and found that they did not match the text content in your[ JSON file](https://github.com/NExT-GPT/NExT-GPT/blob/main/data/IT_data/T-T+X_data). It is possible that you are not using the CC3M dataset to generate T2M data.

  Could you disclose what dataset your T2M data was generated from?

**Comment by linhan0109** [comment]
I have the same question.

**Comment by ZoneFv** [comment]
I have the same question. @ChocoWu

**Comment by ChocoWu** [comment]
@zc-zhao @linhan0109 @ZoneFv , thx for the interest. 
The T2M dataset is generated based on the CC3M dataset, and the image and text content inconsistency will be addressed in future days. 
Actually, when generating embedding, only the captions are needed, since we only utilize the text encoder within the diffusion to generate the embedding.

**Comment by jwzhi** [comment]
When will you address this mismatch issue in T2M dataset? I cannot finetune NextGPT to generate images based on text prompts if this T2M data is missing. 
Even though we can generate embeddings for captions for the CC3M dataset based on the text captions provided json for the T2M dataset. However, I don't have the ground truth images. Is there any suggestions on how we can finetune the models if ground truth images are missing?

**Comment by ChocoWu** [comment]
@jwzhi, thx for the interests. 
I have updated the T2X dataset, please refer to [the updated version](https://github.com/NExT-GPT/NExT-GPT/tree/main/data/IT_data/T-T%2BX_data). 
The T2X data is generated based on `CC3M`, `Webvid-2M-train`, and `Audiocap-train`.
You can retrieve the source images/video/audios based on the `source_data`.  For example:

``` 
{
        "output_modality": "audio",
        "conversation": [
            {
                "from": "human",
                "value": "I'm working on a project that requires the sound of a vehicle engine working at a regular pace, along with a man giving a speech. Can you assist me with that?",
                "input_modality": "text"
            },
            {
                "from": "gpt",
                "value": "Absolutely! I have just the audio clip you need. Imagine yourself transported to the scene: the steady hum of a vehicle engine reverberates in the background, creating an ambient backdrop. Amidst this mechanical symphony, a man's voice takes center stage, delivering an engaging and inspiring speech that captivates the listener's attention.",
                "caption": "A vehicle engine works at regular pace and a man speeches",
                "output_modality": "audio"
            }
        ],
        "source_data": {
            "audiocap_id": 34706,
            "youtube_id": "EvlXd8qHyMI",
            "start_time": 160,
            "caption": "A vehicle engine works at regular pace and a man speeches"
        }
}
```

**Comment by jwzhi** [comment]
Thank you for your effort on this :). It's really helpful.
