### ISSUE TITLE
Problem when running the app demo on part 4

### ISSUE THREAD

**Issue by Tizzzzy** [NExT-GPT/NExT-GPT#39]
**Hi,
I have already downloaded 'nextgpt_7b_tiva_v0' weights from huggingface, but when I run 'bash scripts/app.sh', it gives me this error:**

Setting ds_accelerator to cuda (auto detect)
/home/kjj8053/anaconda3/envs/nextgpt/lib/python3.8/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/home/kjj8053/anaconda3/envs/nextgpt/lib/python3.8/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
/home/kjj8053/research/NExT-GPT/code/model/custom_sd.py:28: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
[!] load base configuration: config/base.yaml
Traceback (most recent call last):
  File "demo_app.py", line 28, in <module>
    args.update(load_config(args))
  File "/home/kjj8053/research/NExT-GPT/code/config/__init__.py", line 27, in load_config
    if args['mode']:
KeyError: 'mode'

**Comment by ChocoWu** [comment]
@Tizzzzy, the bug has been fixed, please refer to the update.
