### ISSUE TITLE
Unable to generate visual

### ISSUE THREAD

**Issue by chiho-5** [NExT-GPT/NExT-GPT#4]
Hi there, NextGPT is a great model and would serve as a good foundation for more formidable models understanding more modalities. I also understand that this is just the initial version nonetheless, model seems to be unable to follow instructions as well generate coherent visual. It also seems like the LLM's text generation ability was heavily impacted

**Comment by chiho-5** [comment]
Dont worry, I've understood what the problem was

**Comment by scofield7419** [comment]
Hi, thanks for your attention and feedback.

It's the case that it sometimes showcases failure generation, e.g., decline to follow instructions. Please try to change the input prompts, to make them more precise, and then things will get much better. I think this will help, as we do it the same way. 
We are on the way optimizing the system, please stay tuned. Thanks!
