### ISSUE TITLE
KeyError: 'lora_r' in demo_app.py

### ISSUE THREAD

**Issue by eeric** [NExT-GPT/NExT-GPT#42]
File "demo_app.py", line 27, in <module>
    model = NextGPTModel(**args)
  File "/NExT-GPT/code/model/anyToImageVideoAudio.py", line 80, in __init__
    r=self.args['lora_r'],
KeyError: 'lora_r'

**Comment by ChocoWu** [comment]
Hi, the bug has been fixed, please check the update. 
Or, you can refer to the solution in [issue #24 ](https://github.com/NExT-GPT/NExT-GPT/issues/24#issuecomment-1751843937).
