### ISSUE TITLE
Using huggingface's pytorch_model.pt, the answer to the error is as follows

### ISSUE THREAD

**Issue by south20** [NExT-GPT/NExT-GPT#51]
Thanks for the colourful work, I'm having some problems running it
![image](https://github.com/NExT-GPT/NExT-GPT/assets/102449159/a372e77a-209f-4ce7-a846-b49b11afd0a8)
text prompt:  ### Human:  hello
### Assistant:
all_gen_img_idx:  []
all_gen_vid_idx:  []
all_gen_aud_idx:  []
text_outputs:  ['surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely surely critical critical
The following is the model loading process which also does not report any obvious errors
![image](https://github.com/NExT-GPT/NExT-GPT/assets/102449159/e0d6eb00-ffe3-4bd2-948d-bbd6c91bf9e4)

**Comment by south20** [comment]
It has been resolved

**Comment by shivam-chandhok** [comment]
How did you resolve this @south20

**Comment by MAXPEACEd** [comment]
same question. How did you resolve this @south20
