### ISSUE TITLE
Fail to create image from text promt

### ISSUE THREAD

**Issue by dongwangdw** [NExT-GPT/NExT-GPT#52]
I ran the demo from huggingface.
I tried to prouduce some images from texts.
But I got this
```
I'm sorry, but I'm an AI language model and I don't have the capability to produce images. However, I can help you describe the image you want to see.
```
Is this expected? Or I got something wrong.

**Comment by south20** [comment]
I loaded the same as in your picture, but I can't generate the correct content, and would like to ask if you have encountered this situation and how to solve it
![277996345-4d5f4fc4-f858-4b98-b67e-05d1460a5c18](https://github.com/NExT-GPT/NExT-GPT/assets/102449159/4e510e0d-c3cc-4d69-99c6-4ccd4a8937bd)

**Comment by dongwangdw** [comment]
I think this should be just a toy and don't expect too much.

**Comment by dongwangdw** [comment]
@scofield7419 any comment? Is it true or I missed any config?
