### ISSUE TITLE
will this support SDXL and even image blending? so far SDXL can't blend images.

### ISSUE THREAD

**Issue by Shaistrong** [NExT-GPT/NExT-GPT#6]

**Comment by scofield7419** [comment]
Hi @Shaistrong, as you see, right now the input end receives only one piece of certain modalities, e.g., one image. So yes the current version does not support combining 2 images together.
But, it is definitely okay to equip SDXL, and change the input logic to support unlimited number of modalities (e.g., more than one image) for image blending, so long as your hardware (GPU) supports that big inputs.
Your idea will be considered in our future upgrade. Or you can try it yourself with our code.
Thanks!

**Comment by Shaistrong** [comment]
> Hi @Shaistrong, as you see, right now the input end receives only one piece of certain modalities, e.g., one image. So yes the current version does not support combining 2 images together. But, it is definitely okay to equip SDXL, and change the input logic to support unlimited number of modalities (e.g., more than one image) for image blending, so long as your hardware (GPU) supports that big inputs. Your idea will be considered in our future upgrade. Or you can try it yourself with our code. Thanks!

Great to hear! Also, DeepSpeed isn't the fastest or most compatible optimization. There is something called "AIT" and something else called "OneFlow" both should be compatible with everything and also provide approximately a 3 times boost. I know how to infer AIT on diffusion models like SDXL, but I'm confident it's just as possible on LLMs and audio models

**Comment by Shaistrong** [comment]
> Hi @Shaistrong, as you see, right now the input end receives only one piece of certain modalities, e.g., one image. So yes the current version does not support combining 2 images together. But, it is definitely okay to equip SDXL, and change the input logic to support unlimited number of modalities (e.g., more than one image) for image blending, so long as your hardware (GPU) supports that big inputs. Your idea will be considered in our future upgrade. Or you can try it yourself with our code. Thanks!

Also, image blending and image input was figured out so no need for multimodal to blend. IPAdapter makes this possible. I think you guys could also infer IPAdapter in this, even more capabilities.

**Comment by yhyu13** [comment]
Is SDXL supported? The readme mention NextGPT used sd 1.5
