### ISSUE TITLE
Weird Output

### ISSUE THREAD

**Issue by shrinivasait** [NExT-GPT/NExT-GPT#68]
When I run the demo code I get this weird output : text_outputs:  ['[IMG3] [VID8] </Img> [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1] [VID20] [VID23] [IMG1]']

Do you happen to have any idea why I am getting this instead of text?

I genuinely appreciate any help you can provide. 

@scofield7419 @ChocoWu @eltociear

**Comment by toooooodo** [comment]
Hi, I have encountered similar problems before. I found that this is because I used the parameters of llama2 to obtain the parameters of vicuna. The correct way is to use llama1.

**Comment by shrinivasait** [comment]
Hi @toooooodo, I have resolved the error by changing the Cuda and torch versions as per the model requirement.

**Comment by manushree635** [comment]
@shrinivasait are you able to generate images
